name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: mkdir $GITHUB_WORKSPACE/docs-build

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: pnpm/action-setup@v2
      with:
        version: 8.2.0

    - uses: actions/checkout@v2
      with:
        path: 'docs-build/docs'

    - name: Cache .pnpm-store
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install documentation
      run: |
        cd $GITHUB_WORKSPACE/docs-build/docs
        pnpm install

    - name: Build documentation
      run: |
        cd $GITHUB_WORKSPACE/docs-build/docs
        npm run build

    - name: Clear public_html
      uses: appleboy/ssh-action@0.1.10
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          rm -rf ~/public_html

    - name: Deploy doc build onto website
      uses: appleboy/scp-action@0.1.4
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "./docs-build/docs/build"
        target: "~/public_html"
        strip_components: 4
